config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :cooperations

  root 'home#index'

  match '/artists',       to: 'artists#index',       via: 'get'
  match '/tickets',       to: 'tickets#index',       via: 'get'
  match '/about_us',      to: 'home#about_us',       via: 'get'
  match '/contact_us',    to: 'home#contact_us',     via: 'get'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  # Associations
  has_many :artist_audios

  accepts_nested_attributes_for :artist_audios,  allow_destroy: true

  # Paperclip
  has_attached_file :image, styles: { thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  # Validates
  validates :name,        presence: true
  validates :description, presence: true
  validates :image,       presence: true
end

app/models/artist_audio.rb
class ArtistAudio < ApplicationRecord
  # Associations
  belongs_to :artist

  # Paperclip
  has_attached_file :audio
  validates_attachment_content_type :audio, content_type: [ 'audio/mpeg',
                                                               'audio/x-mpeg',
                                                               'audio/mp3',
                                                               'audio/x-mp3',
                                                               'audio/mpeg3',
                                                               'audio/x-mpeg3',
                                                               'audio/mpg',
                                                               'audio/x-mpg',
                                                               'audio/x-mpegaudio' ]

  # Validates
  validates :audio, presence: true
end

app/models/cooperation.rb
class Cooperation < ApplicationRecord
  # Validates
  validates :name,       presence: true, length: { maximum: 11 }
  validates :email,      presence: true
  validates :text,       presence: true, length: { maximum: 140 }
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  # Paperclip
  has_attached_file :image, styles: { thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  # Validates
  validates :name,        presence: true, length: { maximum: 10 }
  validates :image,       presence: true
  validates :price,       presence: true, numericality: { greater_then: 0, less_then: 1000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
    @background = 'back-artists'

    if Artist.find_by(name: 'Timmy Trumpet')
    	@bgmodal = 'back-timmy-trumpet'
    elsif Artist.find_by(name: 'Tiesto')
    	@bgmodal = 'back-tiesto'
    elsif Artist.find_by(name: 'Dash Berlin')
    	@bgmodal = 'back-dash-berlin'
    elsif Artist.find_by(name: 'Afrojack')
    	@bgmodal = 'back-frojack'
    elsif Artist.find_by(name: 'Hardwell')
    	@bgmodal = 'back-hardwell'
    elsif Artist.find_by(name: 'Deadmau5')
    	@bgmodal = 'back-deadmau5'    	    	    	
    end
  end
end

app/controllers/cooperations_controller.rb
class CooperationsController < ApplicationController
  def index
    @background = 'back-cooperation'
  end

  def create
    @cooperation = Cooperation.new(cooperation_params)
    if @cooperation.save
      flash[:success] = "Спасибо за заявку! Ожидайте звонка."
      CooperationMailer.cooperation_email(@cooperation).deliver_now
      respond_to do |format|
        format.html
        format.json
      end
      redirect_to :back
    else
      flash[:danger] = "Неверные данные!"
      redirect_to :back
    end
  end

  private

  def cooperation_params
    params.require(:cooperation).permit(:name, :email, :text)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @background = 'back-home'
  end

  def about_us
    @background = 'back-about-us'
  end

  def contact_us
    @background = 'back-contact-us'
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @tickets = Ticket.all
    @background = 'back-tickets'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/cooperations_helper.rb
module CooperationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/artists/_artist_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModalLong<%= i %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content <%= @bgmodal.present? ? @bgmodal : nil %>">
      <div class="modal-header">
        <div>
          <%= image_tag artist.image.url, class: 'img-fluid artist-modal-image' %>
        </div>
        <div>
          <h6><%= artist.name %></h6>
          15 лет<br>
          Киев, Украина<br>
        </div>
        <div class="social-networks-wrapper">
          <ul class="list-inline">
            <li class="list-inline-item social-networks">
              <%= link_to '', 'https://vk.com/', class: 'fa fa-vk', target: '_blank'  %>
            </li>
            <li class="list-inline-item social-networks">
              <%= link_to '', 'https://twitter.com/', class: 'fa fa-twitter', target: '_blank'  %>
            </li>
            <li class="list-inline-item social-networks">
              <%= link_to '', 'https://www.instagram.com/', class: 'fa fa-instagram', target: '_blank'  %>
            </li>
            <li class="list-inline-item social-networks">
              <%= link_to '', 'https://uk-ua.facebook.com/', class: 'fa fa-facebook-square', target: '_blank'  %>
            </li>
          </ul>          
        </div>        
      </div>
      <div class="modal-body">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
      <div class="modal-footer">
        <p>Лучшие композиции артиста</p>
        <p><%= artist.artist_audios.first %></p>
      </div>
    </div>
  </div>
</div>

app/views/artists/artist_modal_template.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModalLong<%= i %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="modal-title" id="exampleModalLongTitle">
          <%= image_tag artist.image.url, class: 'img-fluid artist-modal-image' %>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= artist.name %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/artists/index.html.erb
<div class="artist-wrapper">
  <div class="row">

    <!-- Indent -->
    <div class="col-md-4"></div>

    <!-- Content -->
    <div class="col-12 col-md-4">
      <div class="row">
        <% @artists.each_with_index do |artist, i| %>
              <div class="col-4 col-sm-2 col-md-4 artist"  data-toggle="modal" data-target="#exampleModalLong<%= i %>">
                <%= image_tag artist.image.url, class: 'img-fluid artist-image' %>
                <%= artist.name %>
                <%= render partial: 'artists/artist_modal', locals: { artist: artist, i: i } %>
              </div>
        <% end %>
      </div>
    </div>

    <!-- Indent -->
    <div class="col-md-4"></div>

  </div>
</div>

app/views/cooperations/index.html.erb
<div class="cooperation-wrapper">
  <div class="row">
    <!-- Indent -->
    <div class="col-lg-2">
    </div>

    <!-- Content -->
    <div class="col-12 col-md-12 col-lg-4 cooperation-content">
      <p class="cooperation-text">
        <%= image_tag 'logo-1.png', alt: 'Young People logo', class: 'cooperation-logo' %>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
        incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
        nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore
        eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,
        sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
    </div>

    <!-- Cooperation Form -->
    <div class="col-12 col-md-12 col-lg-4 cooperation-form">
      <%= form_for Cooperation.new do |f| %>
          <%= f.text_field :name, placeholder: 'Имя и фамилия',
                           class: 'form-control coop-form-field',
                           required: true %>
          <%= f.text_field :email, placeholder: 'Ваша почта',
                           class: 'form-control coop-form-field',
                           required: true %>
          <%= f.text_area :text, placeholder: 'Сообщение',
                          class: 'form-control coop-form-field coop-form-field-area' %>
          <%= f.submit 'Отправить', class: 'btn button-cooperation', name: nil %>
      <% end %>
    </div>

    <!-- Indent -->
    <div class="col-lg-2">
    </div>
  </div>
</div>

app/views/home/about_us.html.erb
<div class="about-us-wrapper">
  <div class="row">
    <div class="col-2"></div>
    <div class="col-8">
    <h3>Lorem ipsum</h3>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
    </div>
    <div class="col-2"></div>
  </div>
</div>

app/views/home/contact_us.html.erb
<div class="contact-us-wrapper">
  <div class="row">
    <!-- Indent -->
    <div class="col-lg-2">
    </div>

    <!-- Logo -->
    <div class="col-12 col-md-12 col-lg-4">
      <%= image_tag 'logo-1-orange.png', alt: 'Young People logo', class: 'content-logo' %>
    </div>

    <!-- Content -->
    <div class="col-12 col-md-12 col-lg-3 contact-us-content">
      <span class="contact-us-header">Наши контакты</span>
      <p class="position">Главный менеджер</p>
      <p class="position-info">
        Иван Иванович<br>
        Моб. +390493044951<br>
        Почта. i.ivanovi4@mail.com
      </p>
      <p class="position">Креативный директор</p>
      <p class="position-info">
        Иван Иванович<br>
        Моб. +390493044951<br>
        Почта. i.ivanovi4@mail.com
      </p>
      <p class="position">Создатели</p>
      <p class="position-info">
        Иван Иванович<br>
        Моб. +390493044951<br>
        Почта. i.ivanovi4@mail.com
      </p>
    </div>

    <!-- Indent -->
    <div class="col-lg-3">
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="home-wrapper">
  <div class="row">
    <!-- Indent -->
    <div class="col-lg-2">
    </div>

    <!-- Logo -->
    <div class="col-12 col-md-12 col-lg-4">
      <%= image_tag 'logo-1-a.png', alt: 'Young People logo', class: 'content-logo' %>
    </div>

    <!-- Content -->
    <div class="col-12 col-md-12 col-lg-3 home-content">
      <span class="home-header">Young People Festival</span>
      <p class="home-text">Самый яркий фестиваль танцевальной
        музыки, который вы когда-либо видели в
        Украине. Тонны ярких эмоций и отличное
        настроение вам гарантированы. Бери с
        собой друзей и отрывайся. Ждём тебя 30 и
        31 августа.</p>
    </div>

    <!-- Indent -->
    <div class="col-lg-3">
    </div>

    <!-- Button -->
    <div class="col-12">
      <%= link_to 'Узнать больше', about_us_path, class: 'btn button-home', role: 'button' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YoungPeopleFestival</title>

    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>

    <%= render partial: 'shared/shim' %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body class="<%= @background.present? ? @background : nil %>">
    <div class="wrapper">
      <%= render partial: 'shared/header' %>

      <div class="content-wrapper" id="content">
        <div class="container text-center">
          <%= yield %>
        </div>
      </div>
      
      <%= render partial: 'shared/footer' %>
    </div>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer id="footer-wrapper">
  <div class="container">
    <hr/>
    <div class="text-center">
      <div class="social-networks-wrapper">
        <ul class="list-inline">
          <li class="list-inline-item social-networks">
            <%= link_to '', 'https://vk.com/', class: 'fa fa-vk', target: '_blank'  %>
          </li>
          <li class="list-inline-item social-networks">
            <%= link_to '', 'https://twitter.com/', class: 'fa fa-twitter', target: '_blank'  %>
          </li>
          <li class="list-inline-item social-networks">
            <%= link_to '', 'https://www.instagram.com/', class: 'fa fa-instagram', target: '_blank'  %>
          </li>
          <li class="list-inline-item social-networks">
            <%= link_to '', 'https://uk-ua.facebook.com/', class: 'fa fa-facebook-square', target: '_blank'  %>
          </li>
        </ul>
      </div>
        <small>&copy; 2017 Young People Music. All rights reserved.</small>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<div id="header-wrapper">
  <div class="container">
    <div class="row">

      <!-- Indent -->
      <div class="col col-md-1">
      </div>

      <!-- Header Logo -->
      <div class="col col-12 col-md-2 logo-wrapper">
        <%= link_to (image_tag 'logo-1-1.png', alt: 'Young People logo', class: 'logo'), root_path %>
      </div>

      <!-- Indent -->
      <div class="col col-md-3">
      </div>

      <!-- Header Navigation -->
      <div class="col col-md-6 nav-wrapper navbar navbar-toggleable-md">

        <span onclick="openNav()" onclick="closeNav()" class="burger-button hidden-lg-up">
          <i class="fa fa-bars" aria-hidden="true"></i>
        </span>

        <div id="mySidenav" class="sidenav text-nowrap">
          <a href="javascript:void(0)" class="closebtn hidden-lg-up" onclick="closeNav()">&times;</a>
          <ul class="nav navbar-nav mr-auto">
            <li class="nav-item">
              <%= active_link_to 'О нас', about_us_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= active_link_to 'Артисты', artists_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= active_link_to 'Билеты', tickets_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= active_link_to 'Контакты', contact_us_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= active_link_to 'Сотрудничество', cooperations_path, class: 'nav-link' %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/tickets/_ticket_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="exampleModalLong<%= i %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= ticket.name %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/tickets/index.html.erb
<div class="ticket-wrapper">
  <div class="row">

    <!-- Indent -->
    <div class="col-lg-3"></div>

    <!-- Content -->
    <div class="col-12 col-md-12 col-lg-6">
      <div class="row">
        <% @tickets.each_with_index do |ticket, i| %>
            <div class="col-12 col-md-6 col-lg-6"  data-toggle="modal" data-target="#exampleModalLong<%= i %>">
              <%= image_tag ticket.image.url, class: 'img-fluid' %>
              <%= render partial: 'tickets/ticket_modal', locals: { ticket: ticket, i: i } %>
            </div>
        <% end %>
      </div>
    </div>

    <!-- Indent -->
    <div class="col-lg-3"></div>

  </div>
</div>